### ISSUE TITLE
Changed token validation keys prevent furture authentication

### ISSUE THREAD

**Issue by fsniper** [hashicorp/vault-plugin-auth-jwt#10]
We are using DEX as an oidc provider. It's configured to change signature keys in a timely manner. Whenever the key change occurs, auth-jwt stops working with the error:

```
error validating signature: failed to verify signature: fetching keys oidc: get keys failed Get https://dex.fqdn/keys: context canceled
```

If I reconfigure the jwt backend with 

```
vault write /auth/jwt/config oidc_discovery_url=https://dex.fqdn
```

It starts to work again.

**Comment by avoidik** [comment]
as a workaround you may set `oidc_discovery_ca_pem` explicitly

**Comment by fsniper** [comment]
I tried oidc_discovery_ca_pem, but it's did not work. The problem is the same.

**Comment by avoidik** [comment]
have you tried to set entire certificates chain of https api-endpoint?

**Comment by fsniper** [comment]
@avoidik I tried using the full bundle. Story is the same,

**Comment by fsniper** [comment]
Also, our oidc_discovery_url has a valid letsencrypt certificate. We are not having an issue on the endpoint https certificate validation.

**Comment by fsniper** [comment]
I have followed this to https://github.com/coreos/go-oidc key handling and then to https://github.com/pquerna/cachecontrol.

As far as I understand, goidc caches signature keys until the http expiration date. This is handled by cachecontrol.

Our dex server is giving out these http expiry headers:
```
cache-control | max-age=17734, must-revalidate
date | Fri, 14 Sep 2018 12:04:18 GMT
strict-transport-security | max-age=15724800; includeSubDomains
```
So If I am parsing this correctly, the keys should be valid till *14 Sep 2018 12:04:18 GMT + 17734 seconds (~5hours) = 14 sep 2018 17:04:18 GMT*

I built the cachecontrol sample app and got the expiry date for this page, The output is as expected (approximately same as my calculation):  2018-09-14 16:59:53.00128633 +0000 UTC

So this can be a goidc bug or a vault-plugin-auth-jwt bug. I will investigate a little bit more.

**Comment by jefferai** [comment]
Looking forward to seeing what you find.

**Comment by austingebauer** [comment]
The key caching approach has [changed](https://github.com/coreos/go-oidc/commit/8858d8afe4f964bcbc26a582d84dff7548d177c4) in go-oidc to no longer use cache-control header values, so I'd like to close this issue. Please reopen another issue if there is still a problem here. Thanks!
