### ISSUE TITLE
Save refresh tokens and support obtaining new jwt access tokens from them

### ISSUE THREAD

**Issue by DrDaveD** [hashicorp/vault-plugin-auth-jwt#101]
We would like to use vault to store the "refresh_token" that can come during an OIDC authorization flow, and be able to use that refresh token to obtain short-lived jwt access tokens without having to go through the authorization flow again.  This seems like it would fit in very well with this vault oidc/jwt plugin, but so far I see no hit on the word "refresh" anywhere in this repository.

Do you agree this is a good functionality to have in this plugin?  Is it in an existing plan?  If I were to develop the code in order to speed its availability, would you be willing to provide me with some hints if I get stuck?

Currently our science computing communities ([Open Science Grid](https://opensciencegrid.org) and the [Worldwide LHC Computing Grid](https://wlcg.web.cern.ch/)) has been focusing on another tool called [oidc-agent](https://github.com/indigo-dc/oidc-agent) which does provide that functionality but it is more oriented towards individual users and we're looking for a server-based solution that can be shared by large groups of users.

**Comment by kalafut** [comment]
Hi. Can you explain a little more the flow(s) you envision? Are you proposing to use the refresh/access tokens as a means to authenticate with Vault again, or for other means, and merely capturing & returning them as a result of OIDC auth?

**Comment by DrDaveD** [comment]
Merely as a means of capturing & returning them.  I envision using regular vault access tokens and Kerberos to access vault, and then using the retrieved OIDC access tokens to access other services.

More specifically I want vault to save the OIDC refresh tokens, cache the access tokens, renew the access tokens when needed (that is, when there's less than a configurable amount of life remaining in them) using the refresh tokens, and return access tokens to the user.  OIDC token issuers (optionally) return refresh tokens when the scope "offline_access" is included.

**Comment by kalafut** [comment]
Thanks for the explanation. The basic roles of Vault's auth methods are authenticating to Vault and establishing identity, and the use case you've described does seem to go beyond that.  Data from the auth process is generally not returned, though in some cases portions of it are attached to identity metadata if appropriate. The data retained isn't secret, and is often descriptive properties such as the user's region, or resource group.

Have you considered running the plugin externally (i.e. as an external plugin, overriding the  version bundled in Vault)? You'd be free to customize the functionality as needed.

**Comment by DrDaveD** [comment]
I have actually been trying to figure out how to override the internal plugin with a new copy of the plugin (so far unsuccessfully) but that's just to speed the development process.  I would appreciate hints on how to do it because putting a new copy in the plugin_directory isn't enough.  I tried `vault plugin deregister auth jwt` to get rid of the builtin one but it doesn't go away.  I built the new copy with `make XC_OSARCH=linux/amd64`.

Beyond development, however, I would really rather not have to fork the source code of the whole plugin to add this feature long term.  I would think that this would be something that would be of wide interest to other users and that it would be very helpful to them for this plugin to support it. These are standard OIDC operations.

**Comment by DrDaveD** [comment]
Alternatively, I see that vault secrets engines, for example the aws secrets engine in the [dynamic secrets tutorial](https://learn.hashicorp.com/vault/getting-started/dynamic-secrets), are sometimes able to generate new secrets.  What if we changed this plugin to have the capability of storing the refresh token & access token in a separate oidc secrets engine, and then have the secrets engine take care of renewing the access tokens?  Maybe that would fit better into the vault architecture?

Regarding overriding the builtin plugin, I'm sorry that I just noticed the instructions in the README.md here.   I see 'make dev' is easiest for building, good.  I did the `vault write sys/plugins/catalog/jwt` command but when I do `vault auth enable -plugin-name='jwt' plugin` I get an error 
```
Error enabling jwt auth: Error making API request.

URL: POST https://myserver.name:8200/v1/sys/auth/jwt
Code: 400. Errors:

* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```
I have debugging enabled and /var/log/messages says:
```
Mar 11 18:04:45 myserver vault: 2020-03-11T18:04:45.103-0500 [DEBUG] auth.jwt.auth_jwt_3b36e8bc.jwt: starting plugin: metadata=true path=/etc/vault/plugins/vault-plugin-auth-jwt args=[/etc/vault/plugins/vault-plugin-auth-jwt]
Mar 11 18:04:45 myserver vault: 2020-03-11T18:04:45.110-0500 [DEBUG] auth.jwt.auth_jwt_3b36e8bc.jwt: plugin started: metadata=true path=/etc/vault/plugins/vault-plugin-auth-jwt pid=1439
Mar 11 18:04:45 myserver vault: 2020-03-11T18:04:45.110-0500 [DEBUG] auth.jwt.auth_jwt_3b36e8bc.jwt: waiting for RPC address: metadata=true path=/etc/vault/plugins/vault-plugin-auth-jwt
Mar 11 18:04:45 myserver vault: 2020-03-11T18:04:45.118-0500 [DEBUG] auth.jwt.auth_jwt_3b36e8bc.jwt.vault-plugin-auth-jwt: 2020/03/11 18:04:45 cannot allocate memory: metadata=true
Mar 11 18:04:45 myserver vault: 2020-03-11T18:04:45.118-0500 [ERROR] secrets.system.system_7f5df80d: error occurred during enable credential: path=jwt/ error="Unrecognized remote plugin message:
```

**Comment by DrDaveD** [comment]
I found a core [vault issue](https://github.com/hashicorp/vault/issues/96) requesting a generic oauth2 secrets backend similar to what I'm talking about, and puppetlabs posted a pointer to their [vault-plugin-secrets-oauthapp](https://github.com/puppetlabs/vault-plugin-secrets-oauthapp) that appears to do most of what I want.  The one thing I think it lacks is the ability to authorize and the user to vault, which is what this plugin does.  It doesn't make a lot of sense to ask a user to go through an authorization flow twice, so I think it would be a lot better if this plugin could send the refresh token over to the secrets plugin.

I got plugin loading to work by using the [disable_mlock](https://www.vaultproject.io/docs/configuration/#inlinecode-disable_mlock) option which I understand is only for use during development.  The "cannot allocate memory" message was the clue.

**Comment by DrDaveD** [comment]
I wrote a [vault-plugin-secrets-oauthapp pull request](https://github.com/puppetlabs/vault-plugin-secrets-oauthapp/pull/6) to accept a refresh token through a vault write API.  Next I plan to write a PR for this plugin (vault-plugin-auth-jwt) to write refresh tokens to an optional configured path (where the path can be based on fields in the id token).  I am getting stuck, however, on finding example code where a plugin calls back to a core vault API.  Can you give me a hint on where to find any existing code that does that?  I have found test functions that do it but I assume that it should be done differently from a plugin.

**Comment by kalafut** [comment]
Thanks for the request and PR. This is, however, not a use case we'll be supporting at this time. (Additional comments on #107.)

**Comment by DrDaveD** [comment]
@kalafut Meanwhile I decided that I need to write a smart client program anyway, so how about the much simpler pr #113 which simply returns the refresh token in metadata?
