### ISSUE TITLE
Token verification failed. Invalid ID token nonce

### ISSUE THREAD

**Issue by kuperiudazn** [hashicorp/vault-plugin-auth-jwt#105]
api authentication with oidc is failing on a wrong nonce
https://github.com/hashicorp/vault-plugin-auth-jwt/blob/ca24e89b164dc2193dcc95b077fbc98aa107ed40/path_oidc.go#L254

it seems that nonce that is generated in auth_url isn't the same and login fails

**Comment by kalafut** [comment]
Hi @kuperiudazn . Is the nonce being received? You can enable `verbose_oidc_logging` on the role to inspect the raw token.

**Comment by kuperiudazn** [comment]
Hi @kalafut 

I've enabled verbose_oidc_logging and used audit-hash to inspect The value and I can confirm they are the same.
I've also looked on How it is been done via The UI and The CLI.
From chrome developer tools and The audit log it seems they don't use nonce.

**Comment by kuperiudazn** [comment]
Hi @kalafut 

It seems that I have to pass the nonce to The call back.
It works now.

Thanks for The help
