### ISSUE TITLE
Can't authenticate with OIDC via curl (or any external request)

### ISSUE THREAD

**Issue by axfelix** [hashicorp/vault-plugin-auth-jwt#126]
**Describe the bug**
We can't seem to make OIDC authorization work when initiated from an external CURL request when trying to follow the documentation in https://learn.hashicorp.com/vault/operations/oidc-auth. 

**To Reproduce**
1. Configure vault to use OIDC authorization (eg using Google OAuth) and ensure that the workflow is functional when authenticating via the browser or the `vault` client.
2. Attempt to post to auth URL using `payload.json` (containing `{"role": null, "redirect_uri": "http://localhost:8250/oidc/callback"}`) as in the Vault docs: `curl --request POST --data @payload.json  http://127.0.0.1:8200/v1/auth/oidc/oidc/auth_url`
3. Returned response is:
```
{
  "request_id": "a3010628-1daf-b14d-39dd-a1cdc670be22",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "auth_url": "https://accounts.google.com/o/oauth2/v2/auth?client_id=1048526431489-5dsb27bghce9es3muc3vbb0t42h6l433.apps.googleusercontent.com&nonce=bea85102826d1612f9bf98b3f7b795ceafd2d8ad&redirect_uri=http%3A%2F%2Flocalhost%3A8250%2Foidc%2Fcallback&response_type=code&scope=openid&state=83c879a2d283b6e487a87929d7d63a4b549dead5"
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

When trying to post with `http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback` as the `redirect_uri`, the returned `auth_url` triggers the Google OAuth workflow, but returns this url, `http://localhost:8250/oidc/callback?state=83c879a2d283b6e487a87929d7d63a4b549dead5&code=4%2F2QHope3dmeFJ7gn7X1eXOCyd87mV9vE6EjtHwHfoQ4lOly6h44SHeG4rx_6GHK-nIMisPhJhOqEqHOjJrqSw8mk&scope=openid&authuser=0&prompt=consent#`, which throws a "localhost refused to connect" error in the browser.

Also, just running `curl http://127.0.0.1:8200/v1/auth/oidc/oidc/callback?state=83c879a2d283b6e487a87929d7d63a4b549dead5&code=4%2F2QHope3dmeFJ7gn7X1eXOCyd87mV9vE6EjtHwHfoQ4lOly6h44SHeG4rx_6GHK-nIMisPhJhOqEqHOjJrqSw8mk&nonce=bea85102826d1612f9bf98b3f7b795ceafd2d8ad` returns `{“errors”:[“Vault login failed. No code or id_token received.“]}`

I opened this issue yesterday on the main Vault repo and got some feedback from @kalafut that this isn't possible using regular `curl` calls, but I wanted to clarify that we would be expecting to trigger the regular 3-legged OAuth workflow in which a browser window would be opened, the user would supply credentials, and a token would be returned to the app -- as long as `curl` is able to talk to `https://www.vaultproject.io/api/auth/jwt#oidc-callback`, it should be OK, right?

**Expected behavior**
OAuth workflow should open in a browser window and return token.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.0
* Vault CLI Version (retrieve with `vault version`): 1.4.0
* Server Operating System/Architecture: macOS 10.13.6

Vault server configuration file(s): Server started in dev mode with no additional config provided (verified this also happens in non-dev mode).

**Comment by kalafut** [comment]
Yeah it's pretty standard. After you login in the browser, the redirect will go to whatever is configured on the role and that call will have the OAuth `code` in the URL as a query param. That value needs to be part of the second call to Vault (along with the `state` to complete the flow.
