### ISSUE TITLE
How to set Hosted Domain in OIDC Role config?

### ISSUE THREAD

**Issue by faruqisan** [hashicorp/vault-plugin-auth-jwt#127]
Hi, how to set a hosted domain in OIDC role config? I want to limit the OIDC to selected Google Suites Domains only

for example, I create this role:

```
vault write auth/oidc/role/gmail \
    user_claim="sub" \
    bound_audiences=[YOUR_GOOGLE_API_CLIENT_ID] \
    allowed_redirect_uris=[http://YOUR_VAULT_ADDR//ui/vault/auth/oidc/oidc/callback] \
    policies=demo \
    ttl=1h
```

where I should put my hosted domains configuration?

**Comment by fairclothjm** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault](https://discuss.hashicorp.com/c/vault/30).
