### ISSUE TITLE
JWT Auth config discrepancy between the documentation and code

### ISSUE THREAD

**Issue by afrosimon** [hashicorp/vault-plugin-auth-jwt#128]
I'm running a local Keycloak instance which provides me a JWT and I've run into a confusing situation when configuring vault to accept these JWTs.

As per the official documentation (https://www.vaultproject.io/docs/auth/jwt#jwt-authentication) I've ran this command:

```
vault write auth/jwt/config \
    oidc_discovery_url="https://myco.auth0.com/" \
    oidc_client_id="m5i8bj3iofytj" \
    oidc_client_secret="f4ubv72nfiu23hnsj" \
    default_role="demo"
```

And then I created the role (no issues there AFAIK). And when I tried to login, I hit this error:

```
vault write auth/jwt/login role=demo jwt=SOME_JWT
Error writing data to auth/jwt/login: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/jwt/login
Code: 500. Errors:

* unhandled case during login
```

I've eventually found where this error is raised (https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_login.go#L213). So the switch case is based on authType and based on my reading of that function, providing the OIDC URL + client ID + client secret puts the authType as OIDCFlow - which is not caught by the aforementioned switch case and that's why I'm getting the error! If I do **not** provide the oidc_client_id & oidc_client_secret the authType is OIDCDiscovery and I can log in successfully.

So my question is, is it simply an issue with the vault documentation? Feels like I'm missing something here..

**Comment by dev-e** [comment]
https://github.com/hashicorp/vault-plugin-auth-jwt/issues/72#issuecomment-526746497

**Comment by Eyal-Shalev** [comment]
@afrosimon THANK YOU VERY VERY MUCH.
Hours of headaches solved by your investigation.

**Comment by austingebauer** [comment]
This has been addressed in both [documentation](https://developer.hashicorp.com/vault/docs/auth/jwt#configuration) and [code](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/main/backend.go#L154). I'm going to close this, but feel free to reopen if you still think there is an issue.
