### ISSUE TITLE
oidc: gsuite custom provider groups cannot use bound claims

### ISSUE THREAD

**Issue by adongy** [hashicorp/vault-plugin-auth-jwt#138]
Hi,

With the gsuite provider specific code, fetching groups is done after the bounds claim check, meaning that it will most likely fail.

Notice that `validateBoundClaims` is before `createIdentity` which is where groups are actually fetched.

https://github.com/hashicorp/vault-plugin-auth-jwt/blob/5aa3d0e64032eaf92497a9084df4a1ac0e114b63/path_login.go#L216-L223

https://github.com/hashicorp/vault-plugin-auth-jwt/blob/5aa3d0e64032eaf92497a9084df4a1ac0e114b63/path_login.go#L309-L345

My usecase is using the bound_claims groups so I can restrict a role to members of a specific role. I don't want the users of that group to get a policy for every role they can use.

I believe the same issue applies to the azure custom provider.

**Comment by adongy** [comment]
I can also add that fetching user info has the same issue.

**Comment by ngunia** [comment]
I can confirm that the exact same is true for AzureAD, I was just about to open an issue when I saw this. I am experiencing this issue in my production environment. Users who are a member of >200 groups receive this error: `error validating claims: claim "groups" is missing` which is clearly coming from the error response of `validateBoundClaims()`. The only path to looking up the groups starts in `b.createIdentity()`, so this will never work.

**Comment by night-gold** [comment]
From tests I've done, when you use it with gsuite, any user from your gsuite can use any role created with a bound claim, rendering the role creation useless.
