### ISSUE TITLE
oidc: use claim_mappings for bound_claims

### ISSUE THREAD

**Issue by andysnowden** [hashicorp/vault-plugin-auth-jwt#147]
Hello,

I need a bit of clarification if what I'm trying to do is possible or if I'm hiting a bug.  After looking at the [provider config doc](https://www.vaultproject.io/docs/auth/jwt_oidc_providers) I see where you can import custom directory fields as claim_mappings.  My intention was to use this as part of a bound_claim so I could match a user to a specific role.  We already do this with gsuite and some other OIDC consumers like kibana/elastic.

I was able to successfully configure the claim_mapping however I do not seem to be able to use it for bound_claims.  Is this by design or do I have a issue with my config?

oidc/config:
```json
{
	"default_role": "default_role",
	"oidc_client_id": "<<removed>>",
	"oidc_discovery_url": "https://accounts.google.com",
	"provider_config": {
		"fetch_groups": true,
		"fetch_user_info": true,
		"groups_recurse_max_depth": 5,
		"gsuite_admin_impersonate": "<<removed>>",
		"gsuite_service_account": "/opt/vault/data/service-account.json",
		"provider": "gsuite",
		"user_custom_schemas": "Access_Control"
	}
}
```

role config:
```json
{
	"allowed_redirect_uris": [
		"<<removed>>"
	],
	"bound_claims": {
		"gauth": "admin"
	},
	"bound_claims_type": "string",
	"claim_mappings": {
		"/Access_Control/Vault": "gauth"
	},
	"groups_claim": "groups",
	"policies": [
		"admin"
	],
	"user_claim": "sub",
	"verbose_oidc_logging": true
}
```

Now if I query the google directory api for the custom field it properly shows up
```json
{
	"kind": "admin#directory#user",
	"customSchemas": {
		"Access_Control": {
			"Kibana_DEV": "superuser",
			"Kibana_PROD": "superuser ",
			"Kibana_SIEM": "superuser",
			"Vault": "admin"
		}
	}
}
```

However when I attempt to log into the UI I get `error validating claims: claim "gauth" is missing`

To double check if the claim_mapping is correctly configured I removed the bound_claim and you can see the metadata in the generated token.
```json
{
	"request_id": "b350e4f0-e68d-9a7b-342f-754b6f836093",
	"lease_id": "",
	"renewable": false,
	"lease_duration": 0,
	"data": null,
	"wrap_info": null,
	"warnings": null,
	"auth": {
		"client_token": "<<removed>>",
		"accessor": "<<removed>>",
		"policies": ["admin", "default"],
		"token_policies": ["admin", "default"],
		"metadata": {
			"gauth": "user",
			"role": "admin"
		},
		"lease_duration": 2764800,
		"renewable": true,
		"entity_id": "8fbfa0bf-c855-a0eb-ecc2-0a6aa5d45895",
		"token_type": "service",
		"orphan": true
	}
}
```

I know there's another issue with groups not being usable as claims in #138 Is this related to that or am I misunderstanding claim_mapping usage?

**Comment by austingebauer** [comment]
Hi, @andysnowden. It appears that you've got the correct understanding of `claim_mappings` from taking a look at your role configuration and auth response. Unfortunately, both groups and user information from custom schema fields are affected by the `bound_claims` issue described in https://github.com/hashicorp/vault-plugin-auth-jwt/issues/138. I'm currently working to get a fix up for that issue.

**Comment by andysnowden** [comment]
Thanks for the confirmation @austingebauer 

Looking forward to the fix :)

**Comment by austingebauer** [comment]
Hi, @andysnowden. I've merged a PR with a fix for this issue. You should be able to verify that it works for you by building the plugin manually or waiting for the next Vault release (1.6.1).
