### ISSUE TITLE
Providing file path to the gsuite_service_account in not working anymore

### ISSUE THREAD

**Issue by Ferroman** [hashicorp/vault-plugin-auth-jwt#171]
Providing `service_account.json` as escaped JSON string works as expected, but path to file does not work anymore. Doesn't matter what type of path used - relative or absolute

Vault command:

```
vault write auth/oidc/config - < ./config
```

With absolute path: 
```
...
      "gsuite_service_account": "/home/me/p/vault/service_account.json",
...
```
```
* invalid provider_config: error initializing "gsuite" provider_config: error parsing service account JSON: invalid character '/' looking for beginning of value
```
Relative:
```
...
   "gsuite_service_account": "./service_account.json",
...
```
```
* invalid provider_config: error initializing "gsuite" provider_config: error parsing service account JSON: invalid character '.' looking for beginning of value
```

`service_account.json` exists and acceptable by the vault CLI. 

Vault version: `Vault v1.7.2 (db0e4245d5119b5929e611ea4d9bf66e47f3f208)`

Perhaps I understand that wrong and file should be accessible by the Vault server, not my the CLI?

**Comment by austingebauer** [comment]
Hi, @Ferroman. The `service_account.json` file needs to be readable on the host that Vault server is running on. The Vault CLI doesn't read the file in this case. I just checked to make sure that both options for providing the service account are working in 1.7.2. Let me know if that works for you.

**Comment by Ferroman** [comment]
Thank you for a quick answer! It was unclear for me that service account  file should be present on server during Vault configuration. Documentation said "host", I wasn't sure is this Vault server host, or the host where I run vault CLI.  

I guess escaped JSON string is more secure than file - it is easy to forget remove secret from the server's disk after setup.  

Now it's clear, thank you.

**Comment by mbudim** [comment]
Hi, what is your escaped json file looks like ? I tried but failed. Could you show me paste here ?

**Comment by wokalski** [comment]
`$(cat service-account.json | jq . -c | sed 's/"/\\"/g' | sed 's/\\n/\\\\n/g')` here's a one-liner.
