### ISSUE TITLE
[req] Allow json pointers when specifying a user claim

### ISSUE THREAD

**Issue by taki-mekhalfa** [hashicorp/vault-plugin-auth-jwt#180]
Hello,
Is it possible to allow for JSON pointers when specifying a `user_claim` in JWT roles? 
In some cases, the user is uniquely identified by a non root attribute, as for the following example:

```json
{
  "iat": 1629710930,
  "jti": "1a418f37-4358-4648-b41f-006e62ce0b87",
  "exp": 1629718130,
  "scope": "public",
  "user": {
     "email": "takiedd.mekhalfa@gmail.com",
     "full_name": "Taki Eddine MEKHALFA",
   }
}
```

It would be great if we could do `user_claime="/user/email"`.

I would be happy to work on this feature if you think it can be done without breaking something else.

Thank you,
Taki

**Comment by austingebauer** [comment]
Hi, @taki-mekhalfa! I just noticed that we already have a PR open (https://github.com/hashicorp/vault-plugin-auth-jwt/pull/148) for adding this feature. I'm happy to move that PR forward now that we have some expressed interest in it.

**Comment by taki-mekhalfa** [comment]
Looks promising, thank you!

**Comment by nadendlaprasad** [comment]
@austingebauer  any idea when PR can be merged ?

**Comment by ryanleis** [comment]
Hi @austingebauer can this PR please be revisited and merged. Details have been placed into internal ticket.

**Comment by austingebauer** [comment]
@ryanleis - I would also like to see this capability added to the plugin. I'll be advocating to get this prioritized with my team and will provide an update shortly.
