### ISSUE TITLE
CLI Login fails with POST response mode

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault-plugin-auth-jwt#189]
I have an OIDC auth mounted at `oidc`:

```
$vault read /auth/oidc/config
Key                       Value
---                       -----
bound_issuer              https://x.okta.com
default_role              users
jwks_ca_pem               n/a
jwks_url                  n/a
jwt_supported_algs        []
jwt_validation_pubkeys    []
namespace_in_state        true
oidc_client_id            x
oidc_discovery_ca_pem     n/a
oidc_discovery_url        https://x.okta.com
oidc_response_mode        form_post
oidc_response_types       [id_token]
provider_config           map[]
```

Logging in with the UI works, but it fails when I try to login with the CLI. The page returned is devoid of any information:

```
vault login -method=oidc
```

![image](https://user-images.githubusercontent.com/983101/144385315-43ee5771-77d5-418c-9561-ccd8a3e736f4.png)

And the CLI says

```
Error extracting token: empty response from auth helper
```

Peeking into the network callback from the OIDC IDP, this is the equivalent callback call in Javascript

```javascript
await fetch("http://localhost:8250/oidc/callback", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "en-GB,en;q=0.8,zh-SG;q=0.5,zh;q=0.3",
        "Content-Type": "application/x-www-form-urlencoded",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Sec-GPC": "1"
    },
    "body": "state=st_iLMZx93n1ejny7tQSqlD&id_token=<snip>",
    "method": "POST",
    "mode": "cors"
});
```

So the IDP definitely accepted the configuration and sent the ID token over.

More debug output:

```
$ GODEBUG=http2debug=1 VAULT_STAGING vault login -method=oidc -no-store skip_browser=true
2021/12/02 16:33:39 http2: Transport failed to get client conn for vault:8200: http2: no cached connection was available
2021/12/02 16:33:39 http2: Transport creating client conn 0xc000290f00 to 10.1.1.43:8200
2021/12/02 16:33:39 http2: Transport encoding header ":authority" = "vault:8200"
2021/12/02 16:33:39 http2: Transport encoding header ":method" = "PUT"
2021/12/02 16:33:39 http2: Transport encoding header ":path" = "/v1/auth/oidc/oidc/auth_url"
2021/12/02 16:33:39 http2: Transport encoding header ":scheme" = "https"
2021/12/02 16:33:39 http2: Transport encoding header "x-vault-request" = "true"
2021/12/02 16:33:39 http2: Transport encoding header "content-length" = "102"
2021/12/02 16:33:39 http2: Transport encoding header "accept-encoding" = "gzip"
2021/12/02 16:33:39 http2: Transport encoding header "user-agent" = "Go-http-client/2.0"
2021/12/02 16:33:39 http2: Transport received SETTINGS len=24, settings: MAX_FRAME_SIZE=1048576, MAX_CONCURRENT_STREAMS=250, MAX_HEADER_LIST_SIZE=1048896, INITIAL_WINDOW_SIZE=1048576
2021/12/02 16:33:39 http2: Transport received SETTINGS flags=ACK len=0
2021/12/02 16:33:39 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=983041
2021/12/02 16:33:39 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=102
2021/12/02 16:33:39 http2: Transport received HEADERS flags=END_HEADERS stream=1 len=79
2021/12/02 16:33:39 http2: Transport received DATA flags=END_STREAM stream=1 len=480 data="{\"request_id\":\"35d5b80a-fc46-0d34-21e8-ed618559792d\",\"lease_id\":\"\",\"renewable\":false,\"lease_duration\":0,\"data\":{\"auth_url\":\"https://x.okta.com/oauth2/v1/authorize?client_id=0oa87az0xd8iz2YTS696\\u0026nonce=n_kKQuPzm8r6RcXQwtIS4G\\u0026redirect_uri=htt" (224 bytes omitted)
Complete the login via your OIDC provider. Open the following link in your browser:

    https://x.okta.com/oauth2/v1/authorize?client_id=x&nonce=x&redirect_uri=http%3A%2F%2Flocalhost%3A8250%2Foidc%2Fcallback&response_mode=form_post&response_type=id_token&scope=openid+profile+groups+email&state=x


Waiting for OIDC authentication to complete...
2021/12/02 16:33:46 http2: Transport failed to get client conn for vault:8200: http2: no cached connection was available
Error extracting token: empty response from auth helper
```

## My Hypothesis

From Vault audit logs, I can see something lile

![image](https://user-images.githubusercontent.com/983101/144385423-cc67a12d-4d53-48e5-8bc6-24c8057cef53.png)

```json
{"@level":"info", "@message":"http: TLS handshake error from 10.1.1.83:12451: remote error: tls: bad certificate", "@timestamp":"2021-12-02T08:20:28.617629Z"}
```

Peeking into the code for the helper around these lines: https://github.com/hashicorp/vault-plugin-auth-jwt/blob/d1511e39e4ad5c0994adf4ef84851fb01ffbaef0/cli.go#L156-L171

It seems like the helper uses the plain Go `http` package to make a POST call to Vault server and not the Vault client. I have a self-signed certificate on Vault. Could this explain the bad certificate error? 

Not sure what's going on.

**Comment by DrDaveD** [comment]
Yes, a self-signed certificate would explain the error.  The host certificate has to be able to be verified by the client.

**Comment by DrDaveD** [comment]
Oh I didn't realize, the vault login command line client has an option -tls-skip-verify.  That might work for you for testing, but don't use it for production.

**Comment by lawliet89** [comment]
That does not work because it sets the options for the Vault API client which is not used in that POST request.

**Comment by kalafut** [comment]
We'd probably have to update the Client to do a form post, or add even more options to the CLI.

Do you actually need `form_post`? I know of just one use/request for it, and that mode is basically never asked about. So I'm curious of the situation where the `code` flow won't work.

**Comment by lawliet89** [comment]
I am using the groups information from Okta to assign identity groups to users who login to Vault. 

Normally, with the `code` flow, Okta will return both an ID token and access token and then expect the token consumer to use the profile endpoint to get gorup information.

There are two ways to get group information in the ID Token:

- Use a "fat" token which requires the `form_post` method
- Use a custom authorization server which requires subscribing to a different SKU and costs more.

I cannot do the second option right now and so I am trying the `form_post` method. 

Okta doc: https://support.okta.com/help/s/article/Okta-Groups-or-Attribute-Missing-from-Id-Token?language=en_US

**Comment by kalafut** [comment]
Interesting. I wasn't aware that the extra claims info required a different SKU. Makes we wonder if there isn't perhaps an opportunity to add a custom provider for Okta, like we have for GSuite and Azure. e.g. in GSuite we need to make a trip back to the server to fetch groups as there is simply no way to have them embedded (or wasn't last time we checked): https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/provider_gsuite.go

**Comment by lawliet89** [comment]
That sounds like it might work. Or it could be something more generic since according to the Okta docs, this behaviour is to be expected form the OIDC RFC.

**Comment by lawliet89** [comment]
For future readers, I found a workaround for this issue by adding a new profile claim for the application and switching back to the `code` flow.

In your Okta admin panel, go to Directory -> Profile Editor. Choose your app, and then click "add attribute" to create something like this:

![image](https://user-images.githubusercontent.com/983101/145134309-e57b0080-2c0f-41a2-a939-e6cd1a19c6d1.png)

Then go to your application, assignment and then click the edit icon for each group you have assigned access to.

In the Auth role, change the claim name for groups to the new claim you've just added.

**Comment by austingebauer** [comment]
Hi, @lawliet89! It looks like you were able to get this resolved. I'm going to close the issue, but please re-open it if you feel there is anything else we can do to help here. Thanks!
