### ISSUE TITLE
Plugin issue multiple vault tokens on single OIDC token

### ISSUE THREAD

**Issue by izhukov** [hashicorp/vault-plugin-auth-jwt#2]
When trying to login several times with one OIDC token plugin successfully create multiple tokens.

I believe the expected behavior must be opposite. One vault token for one OIDC token. And the second attempt must return ether same token or error.

**Comment by jefferai** [comment]
That's not how Vault works. We don't ever return the same token for a new authentication attempt.

So long as the JWT is valid, you can use it to get a Vault token, just like so long as your LDAP credentials are valid you can use those, or as long as a GitHub access token you've issued is valid, you can use it to get a new token.

We could potentially add an option to constrain the lifetime of the Vault token to the expiration of the JWT, however, this doesn't really seem necessary, for two reasons:

1) It's better to keep JWT lifetime short so we see the most common use-case being that you have a very short expiry JWT used to get a longer-lived Vault token
2) You can already just set the TTL for the Vault token to be something super small if you are intending for it to be used only for a short period of time (e.g. to make one call).
