### ISSUE TITLE
JWT/OIDC Token Verification

### ISSUE THREAD

**Issue by xkobal** [hashicorp/vault-plugin-auth-jwt#200]
Hi,

I m trying to setup JWT Verification with JWT Token validation on my Vault Server.
My OIDC provider is Auth0.
I have read plenty of documentation and see that there is 3 ways of doing this:

* Static Keys => it works but I don't want to create others JWT Tokens, I want to validate the Auth0 tokens. 
* JWKS => it works
* OIDC Discovery => I am not able to setup. I have tried a lot of different configuration and here is the error: 

```
vault write auth/jwt/config \
    oidc_discovery_url="https://MYDOMAIN.eu.auth0.com/" \
    oidc_client_id=$AUTH0_CLIENT_ID \
    oidc_client_secret=$AUTH0_CLIENT_SECRET \
    bound_issuer="https://MYDOMAIN.eu.auth0.com/"
```

The returned error is: 
```
hvac.exceptions.InvalidRequest: error configuring token validator: unsupported config type, on post http://localhost:8200/v1/auth/jwt/login
```

I don't understand what I am missing on this configuration compared with the 2 others. 

Please also note that OIDC Auth is working with that Auth0 application. 

Thanks for your help. 

Xavier

**Comment by austingebauer** [comment]
Hi, @xkobal. To use OIDC discovery for JWT auth configuration, you'll need to unset the `oidc_client_id` and `oidc_client_secret` in the config. You can unset them by supplying empty strings for both values to the `auth/jwt/config` endpoint similar to:
```
vault write auth/jwt/config \
    oidc_discovery_url="https://MYDOMAIN.eu.auth0.com/" \
    oidc_client_id="" \
    oidc_client_secret="" \
    bound_issuer="https://MYDOMAIN.eu.auth0.com/"
```

**Comment by xkobal** [comment]
It works. Thanks a lot.

**Comment by xkobal** [comment]
Is it something specific to Auth0 or to any OIDC provider ?

**Comment by austingebauer** [comment]
@xkobal - No problem! It's not specific to Auth0. The plugin uses the existence of a client ID and secret to determine if the configuration is for JWT or OIDC auth. For JWT-based auth, those values must be empty.

**Comment by xkobal** [comment]
Thanks for the information. Maybe it's something that would be useful to document ?

**Comment by austingebauer** [comment]
I agree that this could be made more apparent in the docs. I'll make an update 👍
