### ISSUE TITLE
[Help] groups_claim lookup on claim at userinfo not working

### ISSUE THREAD

**Issue by EvertonSA** [hashicorp/vault-plugin-auth-jwt#213]
Hi colleagues,

I have successfully integrated my oidc with vault. 

my oidc provider add some important claims at `/oauth/userinfo`

the bellow default oidc role works:

```
vault write auth/oidc/role/default_role -<<EOF
{
  "allowed_redirect_uris": "ZZZZZZZZ",
  "bound_audiences": "ZZZZZZZZZZ",
  "ttl": "1h",
  "user_claim": "sub",
  "policies": "default",
  "oidc_scopes": "openid",
  "groups_claim": "groups"
}
EOF
```

the bellow default oidc role does not work:

```
vault write auth/oidc/role/default_role -<<EOF
{
  "allowed_redirect_uris": "ZZZZZZZZ",
  "bound_audiences": "ZZZZZZZZZZ",
  "ttl": "1h",
  "user_claim": "sub",
  "policies": "default",
  "oidc_scopes": "openid",
  "groups_claim": "https://gitlab.org/claims/groups/developer"
}
EOF
```

I assume it does not work because as mentioned in gitlab docs `https://gitlab.org/claims/groups/developer` array list is only present on `/oauth/userinfo`.

but...
the bellow works:

```
vault write auth/oidc/role/maintainer-group1 -<<EOF
{
  "allowed_redirect_uris": "ZZZZZZZZZZ",
  "bound_audiences": "ZZZZZZZZZZZZZZZ",
  "ttl": "10m",
  "user_claim": "sub",
  "policies": "group1-maintainer",
  "bound_claims": { "https://gitlab.org/claims/groups/maintainer": ["group1"]}
}
EOF
```

so, it is safe to assume that `default_role` OR `groups_claim`  does not uses userinfo scope and userinfo scope is only used in `bound_claims`??

https://docs.gitlab.com/ee/integration/openid_connect_provider.html

Is there a way to make the default_role from oidc use the userinfo in `groups_claim`?

**Comment by EvertonSA** [comment]
I have also found some people saying that this already worked in vault version 1.6.3

![image](https://user-images.githubusercontent.com/30481051/183409076-d5f2c4fe-b57c-4387-8d76-79c1d4148349.png)


https://forum.gitlab.com/t/hashicorp-vault-oidc-group-membership/51651/13

**Comment by austingebauer** [comment]
Hi, @EvertonSA! The `groups_claim` is evaluated after additional claims are obtained from the userinfo endpoint. You can see this starting at where userinfo is requested [path_oidc.go#L278](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/main/path_oidc.go#L278) to where the claims are parsed using the `groups_claim` for the role [path_oidc.go#L295](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/main/path_oidc.go#L295).

> the bellow default oidc role does not work

Are you able to provide more information as to what you mean by _does not work_? Are you getting an error? Are you not seeing group membership applied correctly? Any more details you can provide will help in troubleshooting this 🙂  

It may also help to turn on [verbose_oidc_logging](https://developer.hashicorp.com/vault/api-docs/auth/jwt#verbose_oidc_logging) if possible so you can see what claims are coming back from Gitlab. The logged claims will contain all ID token claims and userinfo claims merged together. Also, it should not matter if you're using the default role or some specific role -- things should behave the same.

**Comment by austingebauer** [comment]
Hi, @EvertonSA! Were you able to figure out this issue?

**Comment by fairclothjm** [comment]
Due to inactivity, we will close this issue. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
