### ISSUE TITLE
Fail to get groups from google if workplace have more that 1 domain setup

### ISSUE THREAD

**Issue by TheMisterEletric** [hashicorp/vault-plugin-auth-jwt#216]
**Describe the bug**
If i have more that 1 domain configure in my google workplace, i got a erro trying to get the groups:
{
    "error": {
        "code": 404,
        "errors": [
            {
                "domain": "global",
                "message": "Domain not found.",
                "reason": "notFound"
            }
        ],
        "message": "Domain not found."
    }
}

**To Reproduce**
I did a man in the middle to see the request, the request is send without the key "&domain=".
After i replay the request with that key(with also my domain), i got 200 with my groups

**Expected behavior**
Able to set my domain on the api call

**Environment:**
* Vault Server Version 1.12.0
* Vault CLI Version Vault v1.12.0
* Server Operating System/Architecture: MacOS/M1

Vault server configuration file(s):

ui = true
listener "tcp" {
  tls_disable     = 1
  address         = "[::]:8200"
  cluster_address = "[::]:8201"
  telemetry {
    unauthenticated_metrics_access = "true"
  }
}
storage "postgresql" {
  ha_enabled = "true"
  max_idle_connections = 100
  max_parallel = "1000"
}

**Additional context**

https://developers.google.com/admin-sdk/directory/reference/rest/v1/groups/list?apix=true#try-it

**Comment by austingebauer** [comment]
Thank you, @hsimon-hashicorp :)

**Comment by TheMisterEletric** [comment]
Hello,
There any feedback about this?

**Comment by smarkatov** [comment]
Hi. We're having the same issue. Are there any updates on it?

**Comment by austingebauer** [comment]
Hi @TheMisterEletric - I can put a PR together that allows for setting the domain. Would you be able to test it for me? I don't have access to a Google workspace account with multiple domains.

**Comment by austingebauer** [comment]
Closing this as done by #220
