### ISSUE TITLE
Auto-detect the `role_type` to be "jwt" or make the parameter `role_type` mandatory

### ISSUE THREAD

**Issue by hmalphettes** [hashicorp/vault-plugin-auth-jwt#25]
Since the merge of #24 , it is required to pass the new parameter `"role_type": "jwt"` when not using OIDC.
Without specifying `"role_type": "jwt"` configuring a role will return the error: `'allowed_redirect_uris' must be set`.

Would it make sense to detect whether the mount point is configured for OIDC or not and skip the `role_type` entirely?
Otherwise, should we consider making the `role_type` mandatory to avoid having to analyze where missing `allowed_redirect_uris` come from?

My test unit that used to work and now breaks more or less looks like this:
``` go
	config := &vault.CoreConfig{
		CredentialBackends: map[string]logical.Factory{
			"jwt": vaultjwt.Factory,
		},
	}
	core, _, rootToken := vault.TestCoreUnsealedWithConfig(tb, config)
	ln, addr = http.TestServer(tb, core)        
	client, err := makeVaultClient(ln, addr)
	if err != nil {
		return err
	}
	opts := &api.EnableAuthOptions{Type: "jwt"}
	err = client.Sys().EnableAuthWithOptions("jwt", opts)
	if err != nil {
		return err
	}
	payload := map[string]interface{}{
		"jwt_validation_pubkeys": pubKey,
	}
	_, err = client.Logical().Write("auth/jwt/config", payload)
	if err != nil {
		return err
	}
	payload := map[string]interface{}{
		"bound_audiences": pipeline,
		"user_claim":      "requestor",
		"policies":        string[]{"default","test_policy"},
		"ttl":             "5m",
	}
	_, err = client.Logical().Write("auth/jwt/role/testrole", payload)
	if err != nil {
                // here we fail
		return err
	}
```

Thanks for your attention!

**Comment by kalafut** [comment]
A single mount can support both types of roles (provided the respective parameters are set). We did discuss the `role_type` default and the expectation is that most users will prefer OIDC and that would be a more appropriate default (and that it makes sense to even have a default). There will be some adjustments for existing JWT users but they're fairly minor. Note that existing roles will be correctly interpreted as JWT.

That said, I agree that the error message could be confusing if someone isn't aware of the change. I'm inclined to add some detail to that message so people know that there is thing called `role_type` and that it is defaulting to OIDC. That should be a bit more actionable.

**Comment by hmalphettes** [comment]
Ok. Thanks for the explaination.
I understand that if I set an OIDC URL I could configure both types of roles on the same mount.
However, when I leave it empty, the default behavior is a surprise.

Not a big deal at all.

I am proactively adding the `role_type` to my automation to guarantee a smooth upgrade.

**Comment by kalafut** [comment]
To configure OIDC roles you also need to have an `oidc_client` and `oidc_secret` set in the config. You're _just_ ahead of quite a few docs changes that will accompany this change. Feel free to peruse the new text in this PR:  https://github.com/hashicorp/vault/pull/6270

**Comment by hmalphettes** [comment]
OK, thanks again @kalafut .
