### ISSUE TITLE
If a suspend signal is received during the login flow, the suspended process will indefinitely hold the callback port, blocking logins for other system users

### ISSUE THREAD

**Issue by hskiba** [hashicorp/vault-plugin-auth-jwt#250]
I'm proposing to add `signal.SIGTSTP` to the notification channel created during the login flow (see https://github.com/hashicorp/vault-plugin-auth-jwt/blob/17b4d25da27c269342e089e0b290cbba50077842/cli.go#L54C2-L54C39).

We had a user that used Ctrl+Z instead of Ctrl+C when running login on a remote server, and it blocked logins for all other users on the system. This is easily reproducible with Vault:

```shell-session
$ vault login -method=oidc skip_browser=true    
Complete the login via your OIDC provider. Open the following link in your browser:

    <login-link>


Waiting for OIDC authentication to complete...

[1]  + 22969 suspended  vault login -method=oidc -path=azure skip_browser=true
```

Because the suspended process is still holding the port, subsequent logins fail with:

```shell-session
$ vault login -method=oidc skip_browser=true
Error authenticating: listen tcp 127.0.0.1:8250: bind: address already in use
```

I can't think of a situation where it would be valid to suspend the login flow--we always want the timeout of 2 minutes to be enforced, so if we receive a suspend request, just kill the HTTP listener.

I can create a PR for this if agreed.

**Comment by maxcoulombe** [comment]
Fix is now available on the newly released v0.17.1 version. Vault will receive this fix as part of the 1.16.0 release scheduled for February when we update all built-in plugin versions. Cheers and thanks again for that contribution!
