### ISSUE TITLE
Dynamically update verification key with plain JWT

### ISSUE THREAD

**Issue by hiyosi** [hashicorp/vault-plugin-auth-jwt#27]
The specification differs between JWT and OIDC IDToken. For example, the `iss` claim is **not** mandatory in JWT, but it is mandatory in IDToken.
Currently, we need to use `oidc_discovery_url` to dynamically rotate the public key for signature verification. In that case, the JWT must satisfy the specification of ID Token.

Could you support the only jwks endpoint so that we can dynamically update the key in JWT(not OIDC) authentication?

**Comment by kalafut** [comment]
Hi. Are you using the 1.1 beta or an official release? In both cases, you can set `oidc_discovery_url` and it will be used to fetch public keys for JWT verification. If you're using the 1.1 beta, you'll need to create roles with a `role_type` of "jwt" in order to not use the OIDC flows. Am I understanding your question correctly?

**Comment by hiyosi** [comment]
Thanks for reply.
I use Vault '1.0.1'.

If you set `oid_discovery_url` and authenticate using JWT without 'iss' claim.
In that case, Don't you get an error with the following logic?

```
https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_login.go#L225
https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/vendor/github.com/coreos/go-oidc/verify.go#L170
```

**Comment by kalafut** [comment]
OK, I see what you're referring to now. I'll discuss this internally and get back to you.

**Comment by kalafut** [comment]
@hiyosi Supporting verification using a JWKS endpoint would be useful. We're looking into the best way to fit that into the plugin.

**Comment by hiyosi** [comment]
@kalafut Awesome! Thanks for considerations. I hope it will be implemented.
