### ISSUE TITLE
Plugin produce renewable token when "period" is not set in role

### ISSUE THREAD

**Issue by izhukov** [hashicorp/vault-plugin-auth-jwt#3]
When a plugin is configured with some role and "period" don't set for it plugin create a renewable token.

The expected behavior is when a "period" is not set issued token must be not renewable.

**Comment by jefferai** [comment]
The Vault token is renewable up to the maximum TTL you set. This lets you keep the initial TTL short but still constrain it to a maximum lifetime. It also lets clients _reduce_ the lifetime of their given Vault token if they want.
