### ISSUE TITLE
Server cert verification failure during code exchange

### ISSUE THREAD

**Issue by pbohman** [hashicorp/vault-plugin-auth-jwt#39]
The call to `oauth2Config.Exchange(ctx, code)` in path_oidc.go fails due to server certificate validation even though `oidc_discovery_ca_pem` was set with the CA to verify the server certificate. The OIDC discovery call works. But, it looks like the exchange call is made using a default httpclient instead of an httpclient configured with the `oidc_discovery_ca_pem` certificate.

**Comment by kalafut** [comment]
Good catch!  Confirmed the error by upgrading the internal mock server to TLS. Should be a fairly straightforward fix.
