### ISSUE TITLE
Authentication Fails If A Bounded Claim From Server Is A List

### ISSUE THREAD

**Issue by chrissphinx** [hashicorp/vault-plugin-auth-jwt#46]
https://github.com/hashicorp/vault/issues/6685#issuecomment-490500332

It seems like [this loop](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/claims.go#L111) will not function as intended if `actValue` is a list of attributes, but I can't really read Go very well.

What _should_ happen, is that, if the `actValue` is a list, each `expValue` is checked against each `actValue`. Not sure if it should pass on _any_ or _all_ match, though...

**Comment by kalafut** [comment]
You're correct. This initial release was a 1:1 check, and more recently 1:n was added (i.e. success if `actual` matches any of `expected`). I think n:n is useful but your question in the same one I have about what the semantics should be, and I'd prefer to avoid more configuration as this is already a confusing item.

I think the groups example you mentioned on https://github.com/hashicorp/vault/issues/6685 is probably the most typical use case, and my initial opinion is that if supported, then "any match" semantic would be most useful and understandable for the basic cases. For complex relationships, I'd suggest that one look to the identity provider to create a new custom claim using rules logic on the provider side.

**Comment by chrissphinx** [comment]
So, as of 1.1.1 this check is still of the 1:1 variety? Should I pull master and build this module to see if it works?

I myself don't have a use for the n:n variety, but I'm not sure if Gitlab group will add functionality to customize the claims provided at any point.

**Comment by kalafut** [comment]
The 1.1.1 is "1:n", meaning I can do:

```
"bound_claims": {
  "color": ["green", "blue"]
}
```
and if `color` is either green or blue it will match. But a list of colors being received won't work at all. Your groups situation would need the feature enhanced to match against lists. I will discuss this internally.

**Comment by chrissphinx** [comment]
Thanks for spending time on it. We are working around it by bounding `sub`s to list of person I need to have access, but being able to add/remove people from the group on GitLab side of things to grant/revoke access would be very useful to me.

Maybe based on the type returned by `getClaim()` it could switch from "1:n" to "n:1"? I could see this being a "gotcha" for future developers, though...

Good luck!

**Comment by MartinLeedotOrg** [comment]
I bumped up against this today, created #50 to resolve.

**Comment by kalafut** [comment]
We think this change should be made. I'll review the PR soon.

**Comment by kalafut** [comment]
Closed in #50

**Comment by ananthrav** [comment]
@kalafut I guess I'm running into this issue and I'm running Vault 1.2.3. How do I get the latest version of this plugin in Vault. Can I find instructions some where?

**Comment by kalafut** [comment]
@ananthrav This change is in Vault 1.2.0. Can you provide an example of the bound claims you've set up along with claims received from the server with `verbose_oidc_logging` turned on (sensitive data elided).

**Comment by ananthrav** [comment]
@kalafut Sorry false alarm. The issue was related to the way we were passing the bound claims to the API and that was causing Vault to throw an error that bound claims weren't matching. Thanks for the quick response!
