### ISSUE TITLE
error converting claim to string

### ISSUE THREAD

**Issue by splattner** [hashicorp/vault-plugin-auth-jwt#47]
Altought this looks somehow similar to #9 I think its not the same.

I have setup Vault to use a KeyCloack OIDC.
My returned userinfo Data looks like this: 

```
{
    "sub": "0d731a12-e43c-48ef-a033-f2b710bb45fc",
    "email_verified": false,
    "name": "Sebastian Plattner",
    "groups": [
        "group1",
        "group2"
    ],
    "preferred_username": "splattner",
    "given_name": "Sebastian",
    "family_name": "Plattner",
    "email": "...h"
}
```

My Role looks like this

```
[...]
"groups_claim": "groups",
[...]
```

when I try to login I get: `error converting claim 'groups' to string`

The Login with OIDC works when I remove the `groups` claims from the userdata response

What am I doing wrong? Has anybody a Working Config for Keycloack with a Group Membership Mapper?

**Comment by splattner** [comment]
I'm gonna close this again, the Problem was, I had a `claim_mappings` set with `{"groups":"groups"}` and this doesn't work. I guess only strings can be mapped to metadata

**Comment by Typositoire** [comment]
Sorry to hijack this, but I have the same issue and I don't get what you mean by `I had a claim_mappings set with {"groups":"groups"} and this doesn't work.`

**Comment by candlerb** [comment]
This problem also exists for the [standard claim](https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims) `email_verified`:

```
  "claim_mappings": {
    "email": "email",
    "email_verified": "email_verified",
    "foo": "bar"
  }
```

Result:

```
Login error
error converting claim 'email_verified' to string
```
