### ISSUE TITLE
JWT bound constraint check in auth/<role>/config does not consider bound_claims

### ISSUE THREAD

**Issue by shwuandwing** [hashicorp/vault-plugin-auth-jwt#48]
Hi,

For configuring JWT roles (in path_role.go line 401), there is a check that is at least one bound constraint.  However, that check does not consider if bound_claims is non-empty.

i.e.   trying to create a role fails if audience / subject / cidr is empty, but bound_claims is non-empty.

https://github.com/hashicorp/vault-plugin-auth-jwt/blob/eb2915c8f5ae058c6fa5154a41629460f00b9418/path_role.go#L401

   If you agree this is a valid issue, I could make a diff to fix it.

**Comment by kalafut** [comment]
Hi. I think that is a reasonable improvement.

**Comment by shwuandwing** [comment]
#49

**Comment by shwuandwing** [comment]
Fix merged.
