### ISSUE TITLE
  // , Broken link in the README.md

### ISSUE THREAD

**Issue by v6** [hashicorp/vault-plugin-auth-jwt#5]
// , Both of these links to https://www.vaultproject.io/docs/auth/jwt.html lead to a 404 error: 

![image](https://user-images.githubusercontent.com/5750764/42530760-d859efac-8436-11e8-9294-55e01fee12b5.png)

Looks like there's nothing currently in vaultproject.io about Generic JWTs as a supported authentication method.

https://duckduckgo.com/?q=site%3Avaultproject.io+jwt+auth&t=h_&ia=web

https://github.com/hashicorp/vault/search?l=Markdown&q=jwt

**Comment by ryanmickler** [comment]
The correct page is here.
https://github.com/hashicorp/vault/blob/6b4f6b93613dc2bf335860dc890ce4000f92f13a/website/source/docs/auth/jwt.html.md

**Comment by v6** [comment]
// , Thanks Ryan. Just had a meeting about using this.

**Comment by ryanmickler** [comment]
you will also need
https://github.com/hashicorp/vault/blob/6b4f6b93613dc2bf335860dc890ce4000f92f13a/website/source/api/auth/jwt/index.html.md

**Comment by jefferai** [comment]
That's because this isn't released, so the documents are not our our site yet.

**Comment by v6** [comment]
That makes sense

And anyway I have some reading to do to figure out how OIDC works in the mean time
