### ISSUE TITLE
Login without providing role

### ISSUE THREAD

**Issue by izhukov** [hashicorp/vault-plugin-auth-jwt#6]
For now one of the parameter to login endpoint id "role". For our use case, it will be better to drop this parameter. Without this parameter, the plugin must decide what policy to bind to the new token.
To do this properly the role must have a place to fill some binding to user/groups.

@jefferai Is it sane enhancements, WDYT?

**Comment by jefferai** [comment]
I'm not sure I really follow, but I think there could be a config option that specifies a claim that contains the role. So you could encode the role into the JWT itself.
