### ISSUE TITLE
Vault Namespaces are not supported by Azure AD in the plugin's current state

### ISSUE THREAD

**Issue by nebffa** [hashicorp/vault-plugin-auth-jwt#60]
When integrating with Azure AD, Vault Namespaces cannot be used because Azure AD redirect URIs do not support query strings: https://blogs.msdn.microsoft.com/aaddevsup/2018/04/18/query-string-is-not-allowed-in-redirect_uri-for-azure-ad/

Microsoft recommends using the `state` parameter of an OIDC authentication request.

Would it be possible to include the Vault Namespace information in the `state` parameter, and subsequently have the plugin retrieve it upon a successful OIDC request?

**Comment by nebffa** [comment]
Hey @kalafut , I have some spare time at work and could look at doing this work if you like 😄

**Comment by kalafut** [comment]
Hi @nebffa. We're aware of the Azure restriction and are reviewing the options (this approach being one of them). Thanks for the offer to help out. Depending on the number changes to be coordinated between the backend and UI, this one may be a little simpler to manage internally, but again it's all still TBD. And in any case, we appreciate reviewers and testers.

**Comment by nebffa** [comment]
@kalafut cool :)

**Comment by tvoran** [comment]
Hi @nebffa, in my recent testing Azure does now support query parameters in the redirect URIs. Though in Vault 1.6 we changed the default way namespace is passed around in the OIDC flow, such that the namespace query parameter shouldn't be necessary anymore: https://www.vaultproject.io/docs/auth/jwt#redirect-uris, https://www.vaultproject.io/api-docs/auth/jwt#namespace_in_state

Closing this for now, cheers!
