### ISSUE TITLE
OIDC Auth Backend unexpected behavior and errors

### ISSUE THREAD

**Issue by binlab** [hashicorp/vault-plugin-auth-jwt#65]
**Describe the bug**

During using **OIDC Auth Backend** unexpected behavior was observed with different **OAuth** providers. Despite the fact that the `oidc_discovery_url` parameter is indifferent to the slash at the end of the URL but this is not taken into account when checking compliance issuer URLs.

**How To Reproduce and Errors**

**Google:**

```shell
vault write auth/oidc/config \
    oidc_discovery_url="https://accounts.google.com/" \
    oidc_client_id="xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com" \
    oidc_client_secret="xxxxxxxxxxxxxxxxxxxxxxxx" \
    default_role="google"
Error writing data to auth/oidc/config: Error making API request.

URL: PUT https://vault.mycompany.com/v1/auth/oidc/config
Code: 400. Errors:

* error checking oidc discovery URL: error creating provider with given values: oidc: issuer did not match the issuer returned by provider, expected "https://accounts.google.com/" got "https://accounts.google.com"
```

_response from provider:_ 

`curl https://accounts.google.com/.well-known/openid-configuration`
```
{
 "issuer": "https://accounts.google.com",
 "authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
 "token_endpoint": "https://oauth2.googleapis.com/token",
 ...
}
```

**Auth0:**

```shell
vault write auth/oidc/config \
    oidc_discovery_url="https://mycompany.auth0.com" \
    oidc_client_id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", \
    oidc_client_secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", \
    default_role="auth0"
Error writing data to auth/oidc/config: Error making API request.

URL: PUT https://vault.mycompany.com/v1/auth/oidc/config
Code: 400. Errors:

* error checking oidc discovery URL: error creating provider with given values: oidc: issuer did not match the issuer returned by provider, expected "https://mycompany.auth0.com" got "https://mycompany.auth0.com/"
```

_response from provider:_ 

`curl https://mycompany.auth0.com/.well-known/openid-configuration`
```
{
 "issuer":"https://mycompany.auth0.com/",
 "authorization_endpoint":"https://mycompany.auth0.com/authorize",
 "token_endpoint":"https://mycompany.auth0.com/oauth/token",
 ...
}
```

**Expected behavior**
Vault should be indifferent to the format of the URL, for example:

`oidc_discovery_url="https://accounts.google.com"`
and
`oidc_discovery_url="https://accounts.google.com/"`

should be equivalent

**Environment:**
* Vault Server Version: **1.2.1**
* Vault CLI Version: **1.2.1**
* Server Operating System/Architecture: **CentOS 7, x86_64**

**Additional context**
This error was fixed by this PR - https://github.com/coreos/go-oidc/pull/209. Hope it will be merged soon and implemented in a Vault as well.

**Comment by kalafut** [comment]
Hi. We'll pick up the library change if the go-oidc PR is accepted, but I suspect you might get some pushback there. The OIDC spec is pretty unequivocal about the issuer "MUST be identical" (https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation), and in practice you can just configure the issuer to match what the provider is sending.

**Comment by binlab** [comment]
Hello! Yes, this SPEC to prevent MITM attacks but slash at the end of URL not indicate into to an issuer, even more, this methodology to truncate slash used at the beginning of validation code.

```golang
func NewProvider(ctx context.Context, issuer string) (*Provider, error) {
	wellKnown := strings.TrimSuffix(issuer, "/") + "/.well-known/openid-configuration"
	req, err := http.NewRequest("GET", wellKnown, nil)
```

**Comment by kalafut** [comment]
Since the https://github.com/coreos/go-oidc/pull/209 PR was closed unmerged, I do not believe there is an further action for Vault on this issue. I'm assuming that you're able to get things working  by including or omitting the trailing slash, depending on the provider. If that's not the case please let us know.

**Comment by dretechtips** [comment]
This issue seems to be reappearing with my log with Keycloak and Hashicorp Vault. The Keycloak issuer adds a slashing trail to the url, but Vault only accepts non trailing slash URL as valid configuration URL.

```
2024-07-31T01:10:04.225Z [ERROR] auth.oidc.auth_oidc_ff0b4306: error checking oidc discovery URL: error="error creating provider with given values: NewProvider: unable to create provider: oidc: issuer did not match the issuer returned by provider, expected \"https://iam.domain.com/realms/domain/\" got \"https://iam.domain.com/realms/domain\""

```

Version: Vault v1.17.2 (2af5655e364f697a15b1dc2db2c3f85f6ef949f2), built 2024-07-05T15:19:12Z

**Comment by kalafut** [comment]
cc @calvn as I'm no longer at HashiCorp.
