### ISSUE TITLE
OIDC: token_ttl has no effect

### ISSUE THREAD

**Issue by jan-schumacher** [hashicorp/vault-plugin-auth-jwt#66]
I set every possible token_ttl value to 24h in my configuration but without any effect at all.
```
allowed_redirect_uris      [http://localhost:8250/oidc/callback]
bound_audiences            [supersecret]
bound_claims               <nil>
bound_subject              n/a
claim_mappings             <nil>
clock_skew_leeway          0
expiration_leeway          0
groups_claim               n/a
not_before_leeway          0
oidc_scopes                <nil>
role_type                  oidc
token_bound_cidrs          []
token_explicit_max_ttl     24h
token_max_ttl              24h
token_no_default_policy    false
token_num_uses             0
token_period               0s
token_policies             [provisioneer]
token_ttl                  24h
token_type                 default
user_claim                 sub
verbose_oidc_logging       false
```
The servers default token 32 days ttl kept using all the time at login. 

When I set the undocumented 'ttl' value it works just fine.

**Comment by kalafut** [comment]
@jan-schumacher  Thanks for reporting this!  I've reproduced it and see that the code path for manual JWT logins was updated with the token fields, but the OIDC route was not.

**Comment by kalafut** [comment]
@jan-schumacher The fix is in the plugin which you can build yourself if you want, otherwise it will appear in the next minor version of Vault (though not 1.2.2 whose content was already locked). I've also temporary reverted the docs for this plugin.  Thanks again!

**Comment by jan-schumacher** [comment]
@kalafut Thats great! Thanks for fixing it! I will wait for the upcoming release :)
