### ISSUE TITLE
API login broken

### ISSUE THREAD

**Issue by wouterhund** [hashicorp/vault-plugin-auth-jwt#72]
@bks7 @kalafut PR #38 broke API login for us.

This change has broken our vault login using the API. What is the new API to login using an oidc accessToken?

Our process looks like this:

1. App acquires accessToken from oidc identity provider (keycloak)
2. App logs into vault using this accessToken:

        fetch('https://vault.example.com/v1/auth/oidc/login', {
          method: 'POST',
          cache: 'no-cache',
          body: JSON.stringify({
            jwt: accessToken,
          }),
        })

This used to work fine, but no longer does.

**Comment by wouterhund** [comment]
According to the docs this should still work: https://www.vaultproject.io/docs/auth/jwt.html#via-the-api

**Comment by bks7** [comment]
@wouterhund what type of role do you use? PR https://github.com/hashicorp/vault-plugin-auth-jwt/pull/38 disallows login only if the `role_type` is `oidc`. It still should work if the `role_type` is `jwt`.

**Comment by kalafut** [comment]
@wouterhund Note that the default `role_type` is `oidc`, so if your setup wasn't specifying anything previously (e.g. maybe it was created before there even was `role_type`), then you should add `role_type=jwt` as a role parameter.

**Comment by wouterhund** [comment]
We're using `vault write auth/oidc/role/developer bound_audiences=kube-vault user_claim="preferred_username" groups_claim="vault-roles" allowed_redirect_uris='http://localhost:8250/oidc/callback,https://vault.example.com/ui/vault/auth/oidc/oidc/callback'` to create the authentication endpoint, which is also used for login through the web interface and the vault CLI with `-method=oidc`. So I assume we want to keep `role_type=oidc`.

Does changing the `role_type` impact the web/cli login? Should we add a second authentication endpoint with `role_type=jwt`? If so, can that still be used with oidc access tokens?

I can't find any documentation describing `role_type`

**Comment by wouterhund** [comment]
I tried creating another role with `vault write auth/oidc/role/app bound_audiences=kube-vault user_claim="preferred_username" groups_claim="vault-roles" allowed_redirect_uris='http://localhost:8250/oidc/callback,https://vault.example.com/ui/vault/auth/oidc/oidc/callback' role_type=jwt` and changed the login code to:

        fetch('https://vault.example.com/v1/auth/oidc/login', {
          method: 'POST',
          cache: 'no-cache',
          body: JSON.stringify({
            jwt: _keycloak.accessToken,
            role: 'app',
          }),
        })

And now I'm getting "unhandled case during login"

**Comment by bks7** [comment]
@wouterhund It looks like your config doesn't have one of these parameters: https://www.vaultproject.io/api/auth/jwt/index.html#oidc_discovery_url or https://www.vaultproject.io/api/auth/jwt/index.html#jwks_url or https://www.vaultproject.io/api/auth/jwt/index.html#jwt_validation_pubkeys.
Here's how it works -https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_login.go#L98

**Comment by wouterhund** [comment]
@bks7 This is the config:

```
» vault read auth/oidc/config
Key                       Value
---                       -----
bound_issuer              n/a
default_role              developer
jwks_ca_pem               n/a
jwks_url                  n/a
jwt_supported_algs        []
jwt_validation_pubkeys    []
oidc_client_id            kube-vault
oidc_discovery_ca_pem     n/a
oidc_discovery_url        https://login.example.com/sso/realms/example
```

So `oidc_discovery_url` is set, and things work fine in the web interface with the `role_type=oidc` role. Things also used to work fine in the past, before this change.

**Comment by bks7** [comment]
Hmm... I guess since you have` oidc_client_id` and `oidc_client_secret` set in your config than after calling that https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_config.go#L316 it returns as a result - https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_config.go#L316. And this config type isn't handled by the switch https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_login.go#L97 and that's why you get your error. I don't think there's a way when you can utilize in one configuration both workflows oidc and simple jwt token check. 
As for
 > Things also used to work fine in the past, before #38

there was a real threat that someone who get the jwt token in a malicious way could authenticate to Vault simply providing stolen JWT token while we are sure that it's impossible since we use OIDC approach to get JWT token.

**Comment by wouterhund** [comment]
What is the recommended way to get this functionality back? This is a real
show stopper for us.

**Comment by kalafut** [comment]
@wouterhund If you want to both the OIDC flow (for UI/CLI), and to directly provide a JWT to the /login path, you'll want two mounts. The mount config really sets up the flow that the roles will use, and they're exclusive for a given mount. The JWT mount you added should work fine for "/login" once you clear `oidc_client_id` and `oidc_client_secret`. But you'll need to use an OIDC-configured mount for the CLI/UI.

This _is_ a bit cumbersome if you want both login types. There have been some ideas discussed on how to simplify this, but right now I think you need two mounts.

You're right about the docs for `role_type`. We'd updated the API page, but the main docs do need updates for that parameter.

**Comment by wouterhund** [comment]
@kalafut Thanks, will try this soon. Could you please expand on what exactly the vulnerability is that was fixed by #38?

I was under the impression that if you could acquire someone's access_token it was expected that you'd have access to all systems that user has access to, but if I understand the fix correctly, it's designed to alleviate this?

**Comment by kalafut** [comment]
@wouterhund Prior to the fix, if you somehow got ahold of valid JWT, you could send it through the `/login` path even for an OIDC configured role. Now that is prohibited. The only thing you (e.g. your browser) can send Vault is an authorization code received as part of the OIDC login process. Vault can check that the request was recently initiated, and _it_ obtains the JWT from the provider using that auth code, a process which will include client_secret checks, nonce check, etc.

**Comment by primeroz** [comment]
FYI I am having the same problem, 

I had both JWT and OIDC on the same mount and it used to work.

Post upgrade, in my case, OIDC still works but JWT Direct login does not anymore with 

```
* unhandled case during login
```

I will try and split them into 2 mounts

**Comment by primeroz** [comment]
Working fine now that they are split and i removed the oidc settings from the jwt mount

**Comment by wouterhund** [comment]
Login is now working after splitting the mount, but all of the group mappings are broken now, since they reference the mount_accessor. So no policies are granted, and the tokens can't do anything.

I'm now trying to add multiple group aliases, one for each mount_accessor, but for some reason the most recently added overwrites the previous ones. So this still isn't working. Should I be duplicating the groups for each mount point as well as the aliases?

```
» vault list identity/group-alias/id                                                                             1 ↵
Keys
----
389ee00c-7784-33ca-14b9-f813d8ab6fb2
4b5b821c-b6e5-6e08-b004-4fd3523e7dd3

» vault write identity/group-alias name=admins mount_accessor=auth_jwt_a6e47772 canonical_id=07e67599-b3d1-6787-b38f-23474941a870
Error writing data to identity/group-alias: Error making API request.

URL: PUT https://vault.example.org/v1/identity/group-alias
Code: 400. Errors:

* combination of mount and group alias name is already in use

» vault write identity/group-alias name=admins mount_accessor=auth_oidc_3b8836af canonical_id=07e67599-b3d1-6787-b38f-23474941a870
Key             Value
---             -----
canonical_id    07e67599-b3d1-6787-b38f-23474941a870
id              a4c94d5a-c745-5f6e-32ac-08eba5d0358a

» vault list identity/group-alias/id
Keys
----
4b5b821c-b6e5-6e08-b004-4fd3523e7dd3
a4c94d5a-c745-5f6e-32ac-08eba5d0358a
```

I was expecting to wind up with 3 entries. But instead it deleted one and added another.

Can't a flag be added to opt out of this change, since I'm trying to bypass it anyway with multiple mount points? Unless I'm misunderstanding the change has no added value when having both a jwt and oidc mount.

**Comment by primeroz** [comment]
this problem with group alias is by design i am afraid ( https://www.vaultproject.io/docs/secrets/identity/index.html#external-vs-internal-groups )

an external group can only have one alias, last alias set will overwrite the older one

you will need to create 2 groups and 2 aliases

group-jwt - alias-jwt 
gorup-oidc - alias-oidc

since the alias name is what maps to your group as returned in the jwt token you can use the same name

**Comment by wouterhund** [comment]
Thanks for the tip. After rewriting our vault provisioning script to create groups and group aliases for each mount (we sync this information from a git repo) things are finally looking good again.

Both web-based and programmatic login through our oidc provider is now working as before.

**Comment by kalafut** [comment]
👍
