### ISSUE TITLE
Vault login for WSL

### ISSUE THREAD

**Issue by rtselizondo** [hashicorp/vault-plugin-auth-jwt#76]
Currently when performing a vault login from the linux subsystem within windows. The process falls back to presenting a URL instead of opening a browser. 

The code line that detects the OS is [here](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/fa5d6cc5215f1a29ea72bb0f18e14f52419a45bc/cli.go#L144).

There seems to be two ways to detect the WSL system:
First, look at the `/proc/version` file and see if it contains the word microsoft. below is my version file contents for comparison. 
```Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Mon Mar 18 12:02:00 PST 2019```

Second, look at how it's implimented in the azure CLI in python and find a GO equivalent. [here](https://github.com/Azure/azure-cli/blob/779ae8117ae8db7f0cc325932eeebeb683a34445/src/azure-cli-core/azure/cli/core/util.py#L388) is how they detect the WSL and [here](https://github.com/Azure/azure-cli/blob/779ae8117ae8db7f0cc325932eeebeb683a34445/src/azure-cli-core/azure/cli/core/util.py#L364) is how the browser is opened. 

I wanted to put a PR together for this but wanted input on direction first. 

Thanks!

**Comment by kalafut** [comment]
@rtselizondo Hi. Yeah, that detection has be updated a couple times and is tough to check against a wine range of setups. If you can work out a reliable Go equivalent version of the detection and test it out we'd happily accept a PR.

**Comment by rtselizondo** [comment]
#77 /lgtm
