### ISSUE TITLE
sub claim does not match bound subject during login

### ISSUE THREAD

**Issue by michyliao** [hashicorp/vault-plugin-auth-jwt#8]
I am trying to login into vault with jwt token that was generated after I had logged in with google login. I am not 100% sure what my `bound_audiences` and `user_claim` values should be. Currently my config for `auth/jwt/role/demo` set  as
`
bound_subject ="<gcp app engine client id>"
bound_audience="https://accounts.google.com"
user_claim=""
`
When i login as: 
`vault write auth/jwt/login role=demo jwt="<token>"`
it is returning the error 
`sub claim does not match bound subject during login`

**Comment by jefferai** [comment]
Probably you should take a look at the `sub` value and ensure that it matches what you've set.

**Comment by jefferai** [comment]
Closing as there's no response.

**Comment by michyliao** [comment]
I was able to figure this out. 

The JWT token was generated via oauth gsuite.
