### ISSUE TITLE
Match claim values using wildcards or regular expressions

### ISSUE THREAD

**Issue by randomswdev** [hashicorp/vault-plugin-auth-jwt#82]
Currnetly the auth backend requires exact matches on the claim values. But sometimes it could be useful to allow matching just on portions of the claim, like for example all the departments whose name starts with "Engineering-". I can for sure enumerate all such departments that exist today, but I will have to modify the configuration of the backend every time we define a new department.

Is there any intereste and/or plan to implement such an enhancement in the future? We can work also in contributing a change request if the feature can be of interest.

**Comment by randomswdev** [comment]
Submitted a pull request to implement this change: https://github.com/hashicorp/vault-plugin-auth-jwt/pull/89

**Comment by randomswdev** [comment]
The pull request has been merged. So I think this one can be closed. @kalafut what do you think?

**Comment by kalafut** [comment]
Ah yeah. Thanks.

Closed by #89.
