### ISSUE TITLE
JWT plugin broken for all releases higher then 1.1.5

### ISSUE THREAD

**Issue by luedigernet** [hashicorp/vault-plugin-auth-jwt#88]
**The following set up routine worked with vault release v1.1.5 like acharm for us.
All newer releases ( v1.2.0 up to 1.3.0 ) with the same setup are broken.
When we try to login to vault with the commandbelow**

```code
# dana-read-all policy 
cat <<EOF |  vault policy write dana-read-all - 
path "dana/*" {
   capabilities = ["read"]
}
EOF

# dana-full-access policy 
cat <<EOF |  vault policy write dana-full-access - 
path "dana/*" {
   capabilities = ["read", "list", "create","update","delete"]
}
EOF



vault auth enable jwt
vault write auth/jwt/config \
    oidc_discovery_url="https://idam.metrosystems.net" \
    oidc_client_id="MY_CLIENT" \
    oidc_client_secret="MY_SECRET" \
    default_role="demo"

vault write auth/jwt/role/demo \
    bound_audiences="2TR_VAULT"\
    role_type="jwt"\
    user_claim="upn" \
    groups_claim="groups" \
    ttl=1h



JWT_ACCESSOR=$(vault auth list -format=json | jq -r '.["jwt/"].accessor')
DANA_READ_ALL_ID=$(vault write -format=json identity/group name="dana_read_all" \
        policies="dana-read-all" \
        type="external" \
        metadata=organization="METRONOM GmbH"|jq -r .data.id)

vault write identity/group-alias name="platform_custo" \
        mount_accessor=${JWT_ACCESSOR} \
        canonical_id="${DANA_READ_ALL_ID}"


DANA_FULL_ACCESS_ID=$(vault write -format=json identity/group name="dana_full_access" \
        policies="dana-full-access" \
        type="external" \
        metadata=organization="METRONOM GmbH"|jq -r .data.id)

vault write identity/group-alias name="platform_mayhemtest" \
        mount_accessor=${JWT_ACCESSOR} \
        canonical_id="${DANA_FULL_ACCESS_ID}"



JWT=$(get-user-access-token |jq  -r .access_token )
vault write auth/jwt/login role=demo jwt=${JWT}
```

**Since release 1.2.0 up to 1.3.0 we got the following error message when we try to login with the same configuration**

```code
vault write auth/jwt/login role=demo jwt=${JWT}
Error writing data to auth/jwt/login: Error making API request.

URL: PUT https://custo-prod-vault.apps-api-mcdr-001-live2-peng-be-gcw1.metroscales.io/v1/auth/jwt/login
Code: 500. Errors:

* unhandled case during login
```

**Comment by luedigernet** [comment]
I think the below change causes the error because the OIDCFlow Type is never used in 

![image](https://user-images.githubusercontent.com/1688743/69952491-96efd880-14f7-11ea-8257-2973c0e36f8d.png)

**Comment by kalafut** [comment]
@luedigernet Are you trying to use both OIDC and JWT roles on the same backend? I noticed you're configuring client ID/secret but are sending in a JWT manually.

**Comment by luedigernet** [comment]
@kalafut no I want to use only jwt roles at this path. I configured OIDC URL plus OIDC secret because the documentation says so.

**Comment by luedigernet** [comment]
@kalafut I tested it this morning with the following configuration.

```
vault write auth/jwt/config \
    oidc_discovery_url="https://idam.metrosystems.net" \
    default_role="demo"
```

Now I'm wondering if that is a documentation bug or  an false behaivior of  vault because in  releases befor v1.2.0 it worked with both config parameters in place  as mentioned in the documentation 

![image](https://user-images.githubusercontent.com/1688743/70022979-51ceb380-1596-11ea-8e14-ff7ac7976720.png)

At least the  example missleads beginners like me to the false direction.

**Comment by kalafut** [comment]
@luedigernet Glad you got it working (I just got done testing this locally and was going to suggest exactly what you did).  The documentation is not super clear on this part and we'll get that updated. The behavior is expected, but the role_type/config interplay is pretty confusing... and the vague error message isn't too helpful.

**Comment by luedigernet** [comment]
@kalafut  Thanks for your suport. With that clarification I can proceed with my project.
