### ISSUE TITLE
Support provider-specific OIDC processing

### ISSUE THREAD

**Issue by kalafut** [hashicorp/vault-plugin-auth-jwt#90]
The OIDC handling is currently the same for any OIDC-compliant identity provider. In general that works well, but in some cases the functionality could be improved if the plugin was able take provider-specific action as well. There has been some demand for this already:

* Loading more than 200 groups from Azure AD (#78)
* Retrieving GSuite groups (#87)

The challenge will be how to make such additions in a way that keeps the code orderly, and provides a good UX. At a minimum we'd probably want a user to be able to opt in to such handlers, and each one may have its own set of configuration parameters. It would be preferable that path-help not end up listing a union of every option available to any provider.

**Comment by techs07** [comment]
Hi @kalafut 
Do you think if these are related and can be handled here.
[#8979](https://github.com/hashicorp/vault/issues/8979)
[#8780](https://github.com/hashicorp/vault/issues/8780)

**Comment by kalafut** [comment]
Closed by #118
